#server:
#  port: 4331
#
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/nutech_trx
#    username: postgres
#    password: root
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect